import "./globals.css";
import type { Metadata } from "next";
import { Inter, Roboto } from "next/font/google";
import localFont from "next/font/local";
import NavBar from "./NavBar";
import AuthProvider from "./auth/Provider";
import GoogleAnalyticsScript from "./GoogleAnalyticsScript";

const inter = Inter({ subsets: ["latin"] });

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "500"],
  variable: "--font-roboto",
});

const geist = localFont({
  src: "../public/fonts/geist-latin.woff2",
  variable: "--font-geist",
});

export const metadata: Metadata = {
  title: "Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" data-theme="cyberpunk">
      <GoogleAnalyticsScript />
      <body className={`${roboto.variable} ${geist.variable}`}>
        <AuthProvider>
          <NavBar />
        </AuthProvider>
        <main className="p-5">{children}</main>
      </body>
    </html>
  );
}
